// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: arrows.sql

package sqlc

import (
	"context"
)

const insertArrowDirectory = `-- name: InsertArrowDirectory :exec
INSERT INTO arrowdirectory (staindex, long, short, arrptr)
SELECT $1, $2, $3, $4
WHERE NOT EXISTS (
  SELECT 1 FROM arrowdirectory
  WHERE lower(long) = lower($2) OR lower(short) = lower($3) OR arrptr = $4
)
`

type InsertArrowDirectoryParams struct {
	Staindex *int32  `json:"staindex"`
	Long     *string `json:"long"`
	Short    *string `json:"short"`
	Arrptr   int32   `json:"arrptr"`
}

func (q *Queries) InsertArrowDirectory(ctx context.Context, arg InsertArrowDirectoryParams) error {
	_, err := q.db.Exec(ctx, insertArrowDirectory,
		arg.Staindex,
		arg.Long,
		arg.Short,
		arg.Arrptr,
	)
	return err
}

const insertArrowInverse = `-- name: InsertArrowInverse :exec
INSERT INTO arrowinverses (plus, minus)
SELECT $1, $2
WHERE NOT EXISTS (
  SELECT 1 FROM arrowinverses WHERE plus = $1 OR minus = $2
)
`

type InsertArrowInverseParams struct {
	Plus  int32 `json:"plus"`
	Minus int32 `json:"minus"`
}

func (q *Queries) InsertArrowInverse(ctx context.Context, arg InsertArrowInverseParams) error {
	_, err := q.db.Exec(ctx, insertArrowInverse, arg.Plus, arg.Minus)
	return err
}

const listArrowDirectory = `-- name: ListArrowDirectory :many
SELECT staindex, long, short, arrptr
FROM arrowdirectory
ORDER BY arrptr
`

func (q *Queries) ListArrowDirectory(ctx context.Context) ([]Arrowdirectory, error) {
	rows, err := q.db.Query(ctx, listArrowDirectory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Arrowdirectory{}
	for rows.Next() {
		var i Arrowdirectory
		if err := rows.Scan(
			&i.Staindex,
			&i.Long,
			&i.Short,
			&i.Arrptr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArrowInverses = `-- name: ListArrowInverses :many
SELECT plus, minus
FROM arrowinverses
ORDER BY plus
`

func (q *Queries) ListArrowInverses(ctx context.Context) ([]Arrowinverse, error) {
	rows, err := q.db.Query(ctx, listArrowInverses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Arrowinverse{}
	for rows.Next() {
		var i Arrowinverse
		if err := rows.Scan(&i.Plus, &i.Minus); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const truncateArrowDirectory = `-- name: TruncateArrowDirectory :exec
TRUNCATE TABLE arrowdirectory
`

func (q *Queries) TruncateArrowDirectory(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateArrowDirectory)
	return err
}

const truncateArrowInverses = `-- name: TruncateArrowInverses :exec
TRUNCATE TABLE arrowinverses
`

func (q *Queries) TruncateArrowInverses(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateArrowInverses)
	return err
}
