// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: arrows.sql

package sqlc

import (
	"context"
)

const insertArrow = `-- name: InsertArrow :exec
INSERT INTO arrow_directory (arr_ptr, sta_index, long_name, short_name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (arr_ptr) DO NOTHING
`

type InsertArrowParams struct {
	ArrPtr    int32  `json:"arr_ptr"`
	StaIndex  int32  `json:"sta_index"`
	LongName  string `json:"long_name"`
	ShortName string `json:"short_name"`
}

func (q *Queries) InsertArrow(ctx context.Context, arg InsertArrowParams) error {
	_, err := q.db.Exec(ctx, insertArrow,
		arg.ArrPtr,
		arg.StaIndex,
		arg.LongName,
		arg.ShortName,
	)
	return err
}

const insertArrowInverse = `-- name: InsertArrowInverse :exec
INSERT INTO arrow_inverses (plus, minus)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertArrowInverseParams struct {
	Plus  int32 `json:"plus"`
	Minus int32 `json:"minus"`
}

func (q *Queries) InsertArrowInverse(ctx context.Context, arg InsertArrowInverseParams) error {
	_, err := q.db.Exec(ctx, insertArrowInverse, arg.Plus, arg.Minus)
	return err
}

const listArrowInverses = `-- name: ListArrowInverses :many
SELECT plus, minus
FROM arrow_inverses
ORDER BY plus
`

func (q *Queries) ListArrowInverses(ctx context.Context) ([]ArrowInverse, error) {
	rows, err := q.db.Query(ctx, listArrowInverses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArrowInverse{}
	for rows.Next() {
		var i ArrowInverse
		if err := rows.Scan(&i.Plus, &i.Minus); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArrows = `-- name: ListArrows :many
SELECT arr_ptr, sta_index, long_name, short_name
FROM arrow_directory
ORDER BY arr_ptr
`

func (q *Queries) ListArrows(ctx context.Context) ([]ArrowDirectory, error) {
	rows, err := q.db.Query(ctx, listArrows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArrowDirectory{}
	for rows.Next() {
		var i ArrowDirectory
		if err := rows.Scan(
			&i.ArrPtr,
			&i.StaIndex,
			&i.LongName,
			&i.ShortName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
