// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookmarks.sql

package sqlc

import (
	"context"
)

const insertBookmark = `-- name: InsertBookmark :exec
INSERT INTO bookmarks (bookmark, query)
VALUES ($1, $2)
`

type InsertBookmarkParams struct {
	Bookmark string `json:"bookmark"`
	Query    string `json:"query"`
}

func (q *Queries) InsertBookmark(ctx context.Context, arg InsertBookmarkParams) error {
	_, err := q.db.Exec(ctx, insertBookmark, arg.Bookmark, arg.Query)
	return err
}

const listBookmarks = `-- name: ListBookmarks :many
SELECT bookmark, query
FROM bookmarks
`

func (q *Queries) ListBookmarks(ctx context.Context) ([]Bookmark, error) {
	rows, err := q.db.Query(ctx, listBookmarks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bookmark{}
	for rows.Next() {
		var i Bookmark
		if err := rows.Scan(&i.Bookmark, &i.Query); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
