// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookmarks.sql

package sqlc

import (
	"context"
)

const listBookmarks = `-- name: ListBookmarks :many
SELECT Bookmark, Query FROM Bookmarks
`

type ListBookmarksRow struct {
	Bookmark *string `json:"bookmark"`
	Query    *string `json:"query"`
}

func (q *Queries) ListBookmarks(ctx context.Context) ([]ListBookmarksRow, error) {
	rows, err := q.db.Query(ctx, listBookmarks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookmarksRow{}
	for rows.Next() {
		var i ListBookmarksRow
		if err := rows.Scan(&i.Bookmark, &i.Query); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
