// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chapters.sql

package sqlc

import (
	"context"
)

const listChaptersLike = `-- name: ListChaptersLike :many
SELECT DISTINCT Chap FROM Node WHERE lower(Chap) LIKE lower($1) ORDER BY Chap
`

func (q *Queries) ListChaptersLike(ctx context.Context, lower string) ([]*string, error) {
	rows, err := q.db.Query(ctx, listChaptersLike, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var chap *string
		if err := rows.Scan(&chap); err != nil {
			return nil, err
		}
		items = append(items, chap)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
