// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contexts.sql

package sqlc

import (
	"context"
)

const getContextByPtr = `-- name: GetContextByPtr :one
SELECT context, ctxptr
FROM contextdirectory
WHERE ctxptr = $1
`

func (q *Queries) GetContextByPtr(ctx context.Context, ctxptr int32) (Contextdirectory, error) {
	row := q.db.QueryRow(ctx, getContextByPtr, ctxptr)
	var i Contextdirectory
	err := row.Scan(&i.Context, &i.Ctxptr)
	return i, err
}

const getContextByText = `-- name: GetContextByText :one
SELECT context, ctxptr
FROM contextdirectory
WHERE context = $1
`

func (q *Queries) GetContextByText(ctx context.Context, argContext *string) (Contextdirectory, error) {
	row := q.db.QueryRow(ctx, getContextByText, argContext)
	var i Contextdirectory
	err := row.Scan(&i.Context, &i.Ctxptr)
	return i, err
}

const getContextByTextUnaccent = `-- name: GetContextByTextUnaccent :one
SELECT context, ctxptr
FROM contextdirectory
WHERE unaccent(context) = unaccent($1)
`

func (q *Queries) GetContextByTextUnaccent(ctx context.Context, unaccent string) (Contextdirectory, error) {
	row := q.db.QueryRow(ctx, getContextByTextUnaccent, unaccent)
	var i Contextdirectory
	err := row.Scan(&i.Context, &i.Ctxptr)
	return i, err
}

const idempInsertContext = `-- name: IdempInsertContext :one
SELECT ideminsertcontext($1::text, $2::int)::int AS ctxptr
`

type IdempInsertContextParams struct {
	Constr string `json:"constr"`
	Conptr int32  `json:"conptr"`
}

func (q *Queries) IdempInsertContext(ctx context.Context, arg IdempInsertContextParams) (int32, error) {
	row := q.db.QueryRow(ctx, idempInsertContext, arg.Constr, arg.Conptr)
	var ctxptr int32
	err := row.Scan(&ctxptr)
	return ctxptr, err
}

const listContexts = `-- name: ListContexts :many
SELECT context, ctxptr
FROM contextdirectory
ORDER BY ctxptr
`

func (q *Queries) ListContexts(ctx context.Context) ([]Contextdirectory, error) {
	rows, err := q.db.Query(ctx, listContexts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contextdirectory{}
	for rows.Next() {
		var i Contextdirectory
		if err := rows.Scan(&i.Context, &i.Ctxptr); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
