// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contexts.sql

package sqlc

import (
	"context"
)

const getContextByPtr = `-- name: GetContextByPtr :one
SELECT ctx_ptr, context
FROM context_directory
WHERE ctx_ptr = $1
`

func (q *Queries) GetContextByPtr(ctx context.Context, ctxPtr int32) (ContextDirectory, error) {
	row := q.db.QueryRow(ctx, getContextByPtr, ctxPtr)
	var i ContextDirectory
	err := row.Scan(&i.CtxPtr, &i.Context)
	return i, err
}

const getContextByText = `-- name: GetContextByText :one
SELECT ctx_ptr, context
FROM context_directory
WHERE context = $1
`

func (q *Queries) GetContextByText(ctx context.Context, argContext string) (ContextDirectory, error) {
	row := q.db.QueryRow(ctx, getContextByText, argContext)
	var i ContextDirectory
	err := row.Scan(&i.CtxPtr, &i.Context)
	return i, err
}

const insertContext = `-- name: InsertContext :exec
INSERT INTO context_directory (ctx_ptr, context)
VALUES ($1, $2)
ON CONFLICT (ctx_ptr) DO NOTHING
`

type InsertContextParams struct {
	CtxPtr  int32  `json:"ctx_ptr"`
	Context string `json:"context"`
}

func (q *Queries) InsertContext(ctx context.Context, arg InsertContextParams) error {
	_, err := q.db.Exec(ctx, insertContext, arg.CtxPtr, arg.Context)
	return err
}

const listContexts = `-- name: ListContexts :many
SELECT ctx_ptr, context
FROM context_directory
ORDER BY ctx_ptr
`

func (q *Queries) ListContexts(ctx context.Context) ([]ContextDirectory, error) {
	rows, err := q.db.Query(ctx, listContexts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContextDirectory{}
	for rows.Next() {
		var i ContextDirectory
		if err := rows.Scan(&i.CtxPtr, &i.Context); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxCtxPtr = `-- name: MaxCtxPtr :one
SELECT COALESCE(max(ctx_ptr), -1)::int AS max_ptr
FROM context_directory
`

func (q *Queries) MaxCtxPtr(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, maxCtxPtr)
	var max_ptr int32
	err := row.Scan(&max_ptr)
	return max_ptr, err
}
