// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: edges.sql

package sqlc

import (
	"context"
)

const deleteEdgesForNode = `-- name: DeleteEdgesForNode :exec
DELETE FROM edge
WHERE (src_class = $1 AND src_cptr = $2)
   OR (dst_class = $1 AND dst_cptr = $2)
`

type DeleteEdgesForNodeParams struct {
	SrcClass int32 `json:"src_class"`
	SrcCptr  int32 `json:"src_cptr"`
}

func (q *Queries) DeleteEdgesForNode(ctx context.Context, arg DeleteEdgesForNodeParams) error {
	_, err := q.db.Exec(ctx, deleteEdgesForNode, arg.SrcClass, arg.SrcCptr)
	return err
}

const getNeighboursByType = `-- name: GetNeighboursByType :many
SELECT e.arr, e.wgt, e.ctx, e.dst_class, e.dst_cptr
FROM edge e
WHERE e.src_class = $1
  AND e.src_cptr = $2
  AND e.st = st_type_from_int($3)
  AND e.arr <> 0
LIMIT $4
`

type GetNeighboursByTypeParams struct {
	SrcClass int32 `json:"src_class"`
	SrcCptr  int32 `json:"src_cptr"`
	I        int32 `json:"i"`
	Limit    int32 `json:"limit"`
}

type GetNeighboursByTypeRow struct {
	Arr      int32   `json:"arr"`
	Wgt      float32 `json:"wgt"`
	Ctx      int32   `json:"ctx"`
	DstClass int32   `json:"dst_class"`
	DstCptr  int32   `json:"dst_cptr"`
}

func (q *Queries) GetNeighboursByType(ctx context.Context, arg GetNeighboursByTypeParams) ([]GetNeighboursByTypeRow, error) {
	rows, err := q.db.Query(ctx, getNeighboursByType,
		arg.SrcClass,
		arg.SrcCptr,
		arg.I,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNeighboursByTypeRow{}
	for rows.Next() {
		var i GetNeighboursByTypeRow
		if err := rows.Scan(
			&i.Arr,
			&i.Wgt,
			&i.Ctx,
			&i.DstClass,
			&i.DstCptr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEdge = `-- name: InsertEdge :exec
INSERT INTO edge (src_class, src_cptr, dst_class, dst_cptr, arr, wgt, ctx, st)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT DO NOTHING
`

type InsertEdgeParams struct {
	SrcClass int32   `json:"src_class"`
	SrcCptr  int32   `json:"src_cptr"`
	DstClass int32   `json:"dst_class"`
	DstCptr  int32   `json:"dst_cptr"`
	Arr      int32   `json:"arr"`
	Wgt      float32 `json:"wgt"`
	Ctx      int32   `json:"ctx"`
	St       StType  `json:"st"`
}

func (q *Queries) InsertEdge(ctx context.Context, arg InsertEdgeParams) error {
	_, err := q.db.Exec(ctx, insertEdge,
		arg.SrcClass,
		arg.SrcCptr,
		arg.DstClass,
		arg.DstCptr,
		arg.Arr,
		arg.Wgt,
		arg.Ctx,
		arg.St,
	)
	return err
}

const listEdgesFrom = `-- name: ListEdgesFrom :many
SELECT src_class, src_cptr, dst_class, dst_cptr, arr, wgt, ctx, st
FROM edge
WHERE src_class = $1 AND src_cptr = $2
`

type ListEdgesFromParams struct {
	SrcClass int32 `json:"src_class"`
	SrcCptr  int32 `json:"src_cptr"`
}

func (q *Queries) ListEdgesFrom(ctx context.Context, arg ListEdgesFromParams) ([]Edge, error) {
	rows, err := q.db.Query(ctx, listEdgesFrom, arg.SrcClass, arg.SrcCptr)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Edge{}
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.SrcClass,
			&i.SrcCptr,
			&i.DstClass,
			&i.DstCptr,
			&i.Arr,
			&i.Wgt,
			&i.Ctx,
			&i.St,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEdgesFromByST = `-- name: ListEdgesFromByST :many
SELECT src_class, src_cptr, dst_class, dst_cptr, arr, wgt, ctx, st
FROM edge
WHERE src_class = $1 AND src_cptr = $2 AND st = $3
LIMIT $4
`

type ListEdgesFromBySTParams struct {
	SrcClass int32  `json:"src_class"`
	SrcCptr  int32  `json:"src_cptr"`
	St       StType `json:"st"`
	Limit    int32  `json:"limit"`
}

func (q *Queries) ListEdgesFromByST(ctx context.Context, arg ListEdgesFromBySTParams) ([]Edge, error) {
	rows, err := q.db.Query(ctx, listEdgesFromByST,
		arg.SrcClass,
		arg.SrcCptr,
		arg.St,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Edge{}
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.SrcClass,
			&i.SrcCptr,
			&i.DstClass,
			&i.DstCptr,
			&i.Arr,
			&i.Wgt,
			&i.Ctx,
			&i.St,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEdgesTo = `-- name: ListEdgesTo :many
SELECT src_class, src_cptr, dst_class, dst_cptr, arr, wgt, ctx, st
FROM edge
WHERE dst_class = $1 AND dst_cptr = $2
`

type ListEdgesToParams struct {
	DstClass int32 `json:"dst_class"`
	DstCptr  int32 `json:"dst_cptr"`
}

func (q *Queries) ListEdgesTo(ctx context.Context, arg ListEdgesToParams) ([]Edge, error) {
	rows, err := q.db.Query(ctx, listEdgesTo, arg.DstClass, arg.DstCptr)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Edge{}
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.SrcClass,
			&i.SrcCptr,
			&i.DstClass,
			&i.DstCptr,
			&i.Arr,
			&i.Wgt,
			&i.Ctx,
			&i.St,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
