// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: graph_fns.sql

package sqlc

import (
	"context"
)

const allNCPathsAsLinks = `-- name: AllNCPathsAsLinks :one
SELECT allncpathsaslinks(
  $1::text::nodeptr[],
  $2::text,
  $3::boolean,
  COALESCE($4::text[], ARRAY[]::text[]),
  $5::text,
  $6::int,
  $7::int
)::text AS paths
`

type AllNCPathsAsLinksParams struct {
	Column1 string   `json:"column_1"`
	Column2 string   `json:"column_2"`
	Column3 bool     `json:"column_3"`
	Column4 []string `json:"column_4"`
	Column5 string   `json:"column_5"`
	Column6 int32    `json:"column_6"`
	Column7 int32    `json:"column_7"`
}

// $1 = text literal of nodeptr[] e.g. {"(1,0)","(2,1)"}
func (q *Queries) AllNCPathsAsLinks(ctx context.Context, arg AllNCPathsAsLinksParams) (string, error) {
	row := q.db.QueryRow(ctx, allNCPathsAsLinks,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	var paths string
	err := row.Scan(&paths)
	return paths, err
}

const allPathsAsLinks = `-- name: AllPathsAsLinks :one
SELECT allpathsaslinks(ROW($1::int, $2::int)::nodeptr, $3::text, $4::int, $5::int)::text AS paths
`

type AllPathsAsLinksParams struct {
	Column1 int32  `json:"column_1"`
	Column2 int32  `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 int32  `json:"column_4"`
	Column5 int32  `json:"column_5"`
}

func (q *Queries) AllPathsAsLinks(ctx context.Context, arg AllPathsAsLinksParams) (string, error) {
	row := q.db.QueryRow(ctx, allPathsAsLinks,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var paths string
	err := row.Scan(&paths)
	return paths, err
}

const callDeleteChapter = `-- name: CallDeleteChapter :exec
SELECT deletechapter($1)
`

func (q *Queries) CallDeleteChapter(ctx context.Context, chapter string) error {
	_, err := q.db.Exec(ctx, callDeleteChapter, chapter)
	return err
}

const constraintPathsAsLinks = `-- name: ConstraintPathsAsLinks :one
SELECT constraintpathsaslinks(
  $1::text::nodeptr[],
  $2::text,
  $3::boolean,
  COALESCE($4::text[], ARRAY[]::text[]),
  COALESCE($5::int[], ARRAY[]::int[]),
  COALESCE($6::int[], ARRAY[]::int[]),
  $7::int,
  $8::int
)::text AS paths
`

type ConstraintPathsAsLinksParams struct {
	Column1 string   `json:"column_1"`
	Column2 string   `json:"column_2"`
	Column3 bool     `json:"column_3"`
	Column4 []string `json:"column_4"`
	Column5 []int32  `json:"column_5"`
	Column6 []int32  `json:"column_6"`
	Column7 int32    `json:"column_7"`
	Column8 int32    `json:"column_8"`
}

func (q *Queries) ConstraintPathsAsLinks(ctx context.Context, arg ConstraintPathsAsLinksParams) (string, error) {
	row := q.db.QueryRow(ctx, constraintPathsAsLinks,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
	)
	var paths string
	err := row.Scan(&paths)
	return paths, err
}

const fwdConeAsLinks = `-- name: FwdConeAsLinks :many
SELECT x::text AS link
FROM unnest(fwdconeaslinks(ROW($1::int, $2::int)::nodeptr, $3::int, $4::int, $5::int)) AS x
`

type FwdConeAsLinksParams struct {
	Column1 int32 `json:"column_1"`
	Column2 int32 `json:"column_2"`
	Column3 int32 `json:"column_3"`
	Column4 int32 `json:"column_4"`
	Column5 int32 `json:"column_5"`
}

func (q *Queries) FwdConeAsLinks(ctx context.Context, arg FwdConeAsLinksParams) ([]string, error) {
	rows, err := q.db.Query(ctx, fwdConeAsLinks,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var link string
		if err := rows.Scan(&link); err != nil {
			return nil, err
		}
		items = append(items, link)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fwdConeAsNodes = `-- name: FwdConeAsNodes :many

SELECT (u).chan::int AS chan, (u).cptr::int AS cptr
FROM unnest(fwdconeasnodes(ROW($1::int, $2::int)::nodeptr, $3::int, $4::int, $5::int)) AS u
`

type FwdConeAsNodesParams struct {
	Column1 int32 `json:"column_1"`
	Column2 int32 `json:"column_2"`
	Column3 int32 `json:"column_3"`
	Column4 int32 `json:"column_4"`
	Column5 int32 `json:"column_5"`
}

type FwdConeAsNodesRow struct {
	Chan int32 `json:"chan"`
	Cptr int32 `json:"cptr"`
}

// Graph PL/pgSQL wrappers (functions from 000002_functions).
// Composite / array results as text for existing Go parsers.
// nodeptr[] / int[] inputs often passed as text casts so sqlc's analyzer stays happy.
func (q *Queries) FwdConeAsNodes(ctx context.Context, arg FwdConeAsNodesParams) ([]FwdConeAsNodesRow, error) {
	rows, err := q.db.Query(ctx, fwdConeAsNodes,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FwdConeAsNodesRow{}
	for rows.Next() {
		var i FwdConeAsNodesRow
		if err := rows.Scan(&i.Chan, &i.Cptr); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fwdPathsAsLinks = `-- name: FwdPathsAsLinks :one
SELECT fwdpathsaslinks(ROW($1::int, $2::int)::nodeptr, $3::int, $4::int, $5::int)::text AS paths
`

type FwdPathsAsLinksParams struct {
	Column1 int32 `json:"column_1"`
	Column2 int32 `json:"column_2"`
	Column3 int32 `json:"column_3"`
	Column4 int32 `json:"column_4"`
	Column5 int32 `json:"column_5"`
}

func (q *Queries) FwdPathsAsLinks(ctx context.Context, arg FwdPathsAsLinksParams) (string, error) {
	row := q.db.QueryRow(ctx, fwdPathsAsLinks,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var paths string
	err := row.Scan(&paths)
	return paths, err
}

const getAppointments = `-- name: GetAppointments :many
SELECT x::text AS appointment
FROM unnest(getappointments(
  $1::int,
  $2::int,
  $3::int,
  $4::text,
  COALESCE($5::text[], ARRAY[]::text[]),
  $6::boolean
)) AS x
`

type GetAppointmentsParams struct {
	Column1 int32    `json:"column_1"`
	Column2 int32    `json:"column_2"`
	Column3 int32    `json:"column_3"`
	Column4 string   `json:"column_4"`
	Column5 []string `json:"column_5"`
	Column6 bool     `json:"column_6"`
}

func (q *Queries) GetAppointments(ctx context.Context, arg GetAppointmentsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getAppointments,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var appointment string
		if err := rows.Scan(&appointment); err != nil {
			return nil, err
		}
		items = append(items, appointment)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConstrainedFwdLinks = `-- name: GetConstrainedFwdLinks :one
SELECT getconstrainedfwdlinks(
  ROW($1::int, $2::int)::nodeptr,
  $3::text,
  $4::boolean,
  COALESCE($5::text[], ARRAY[]::text[]),
  $6::text::nodeptr[],
  $7::int,
  COALESCE($8::int[], ARRAY[]::int[]),
  $9::int
)::text AS links
`

type GetConstrainedFwdLinksParams struct {
	Column1 int32    `json:"column_1"`
	Column2 int32    `json:"column_2"`
	Column3 string   `json:"column_3"`
	Column4 bool     `json:"column_4"`
	Column5 []string `json:"column_5"`
	Column6 string   `json:"column_6"`
	Column7 int32    `json:"column_7"`
	Column8 []int32  `json:"column_8"`
	Column9 int32    `json:"column_9"`
}

func (q *Queries) GetConstrainedFwdLinks(ctx context.Context, arg GetConstrainedFwdLinksParams) (string, error) {
	row := q.db.QueryRow(ctx, getConstrainedFwdLinks,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
	)
	var links string
	err := row.Scan(&links)
	return links, err
}
