// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lastseen.sql

package sqlc

import (
	"context"
)

const callLastSawNPtr = `-- name: CallLastSawNPtr :exec
SELECT LastSawNPtr(ROW($1::int, $2::int)::nodeptr, $3)
`

type CallLastSawNPtrParams struct {
	Column1 int32  `json:"column_1"`
	Column2 int32  `json:"column_2"`
	Name    string `json:"name"`
}

func (q *Queries) CallLastSawNPtr(ctx context.Context, arg CallLastSawNPtrParams) error {
	_, err := q.db.Exec(ctx, callLastSawNPtr, arg.Column1, arg.Column2, arg.Name)
	return err
}

const callLastSawSection = `-- name: CallLastSawSection :exec
SELECT LastSawSection($1)
`

func (q *Queries) CallLastSawSection(ctx context.Context, this string) error {
	_, err := q.db.Exec(ctx, callLastSawSection, this)
	return err
}

const getLastSeenByNPtr = `-- name: GetLastSeenByNPtr :one
SELECT section,
       EXTRACT(EPOCH FROM first)::float8 AS first_epoch,
       EXTRACT(EPOCH FROM last)::float8 AS last_epoch,
       delta,
       freq,
       EXTRACT(EPOCH FROM (NOW() - last))::float8 AS ndelta
FROM lastseen
WHERE nptr = ROW($1::int, $2::int)::nodeptr
`

type GetLastSeenByNPtrParams struct {
	Column1 int32 `json:"column_1"`
	Column2 int32 `json:"column_2"`
}

type GetLastSeenByNPtrRow struct {
	Section    *string  `json:"section"`
	FirstEpoch float64  `json:"first_epoch"`
	LastEpoch  float64  `json:"last_epoch"`
	Delta      *float32 `json:"delta"`
	Freq       *int32   `json:"freq"`
	Ndelta     float64  `json:"ndelta"`
}

func (q *Queries) GetLastSeenByNPtr(ctx context.Context, arg GetLastSeenByNPtrParams) (GetLastSeenByNPtrRow, error) {
	row := q.db.QueryRow(ctx, getLastSeenByNPtr, arg.Column1, arg.Column2)
	var i GetLastSeenByNPtrRow
	err := row.Scan(
		&i.Section,
		&i.FirstEpoch,
		&i.LastEpoch,
		&i.Delta,
		&i.Freq,
		&i.Ndelta,
	)
	return i, err
}

const listAllLastSeenNPtrs = `-- name: ListAllLastSeenNPtrs :many
SELECT (nptr).chan::int AS chan, (nptr).cptr::int AS cptr
FROM lastseen
`

type ListAllLastSeenNPtrsRow struct {
	Chan int32 `json:"chan"`
	Cptr int32 `json:"cptr"`
}

func (q *Queries) ListAllLastSeenNPtrs(ctx context.Context) ([]ListAllLastSeenNPtrsRow, error) {
	rows, err := q.db.Query(ctx, listAllLastSeenNPtrs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllLastSeenNPtrsRow{}
	for rows.Next() {
		var i ListAllLastSeenNPtrsRow
		if err := rows.Scan(&i.Chan, &i.Cptr); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLastSeen = `-- name: ListLastSeen :many
SELECT section,
       (nptr).chan::int AS chan,
       (nptr).cptr::int AS cptr,
       EXTRACT(EPOCH FROM first)::float8 AS first_epoch,
       EXTRACT(EPOCH FROM last)::float8 AS last_epoch,
       delta,
       freq,
       EXTRACT(EPOCH FROM (NOW() - last))::float8 AS ndelta
FROM lastseen
ORDER BY section
`

type ListLastSeenRow struct {
	Section    *string  `json:"section"`
	Chan       int32    `json:"chan"`
	Cptr       int32    `json:"cptr"`
	FirstEpoch float64  `json:"first_epoch"`
	LastEpoch  float64  `json:"last_epoch"`
	Delta      *float32 `json:"delta"`
	Freq       *int32   `json:"freq"`
	Ndelta     float64  `json:"ndelta"`
}

func (q *Queries) ListLastSeen(ctx context.Context) ([]ListLastSeenRow, error) {
	rows, err := q.db.Query(ctx, listLastSeen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLastSeenRow{}
	for rows.Next() {
		var i ListLastSeenRow
		if err := rows.Scan(
			&i.Section,
			&i.Chan,
			&i.Cptr,
			&i.FirstEpoch,
			&i.LastEpoch,
			&i.Delta,
			&i.Freq,
			&i.Ndelta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentLastSeenNPtrs = `-- name: ListRecentLastSeenNPtrs :many
SELECT (nptr).chan::int AS chan, (nptr).cptr::int AS cptr
FROM lastseen
WHERE last > NOW() - make_interval(hours => $1)
`

type ListRecentLastSeenNPtrsRow struct {
	Chan int32 `json:"chan"`
	Cptr int32 `json:"cptr"`
}

func (q *Queries) ListRecentLastSeenNPtrs(ctx context.Context, hours int32) ([]ListRecentLastSeenNPtrsRow, error) {
	rows, err := q.db.Query(ctx, listRecentLastSeenNPtrs, hours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentLastSeenNPtrsRow{}
	for rows.Next() {
		var i ListRecentLastSeenNPtrsRow
		if err := rows.Scan(&i.Chan, &i.Cptr); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
