// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lastseen.sql

package sqlc

import (
	"context"
)

const getLastSeenByNPtr = `-- name: GetLastSeenByNPtr :one
SELECT section, class, cptr,
       EXTRACT(EPOCH FROM first)::float8 AS first_epoch,
       EXTRACT(EPOCH FROM last)::float8 AS last_epoch,
       delta, freq,
       EXTRACT(EPOCH FROM (now() - last))::float8 AS ndelta
FROM last_seen
WHERE class = $1 AND cptr = $2
`

type GetLastSeenByNPtrParams struct {
	Class *int32 `json:"class"`
	Cptr  *int32 `json:"cptr"`
}

type GetLastSeenByNPtrRow struct {
	Section    *string `json:"section"`
	Class      *int32  `json:"class"`
	Cptr       *int32  `json:"cptr"`
	FirstEpoch float64 `json:"first_epoch"`
	LastEpoch  float64 `json:"last_epoch"`
	Delta      float32 `json:"delta"`
	Freq       int32   `json:"freq"`
	Ndelta     float64 `json:"ndelta"`
}

func (q *Queries) GetLastSeenByNPtr(ctx context.Context, arg GetLastSeenByNPtrParams) (GetLastSeenByNPtrRow, error) {
	row := q.db.QueryRow(ctx, getLastSeenByNPtr, arg.Class, arg.Cptr)
	var i GetLastSeenByNPtrRow
	err := row.Scan(
		&i.Section,
		&i.Class,
		&i.Cptr,
		&i.FirstEpoch,
		&i.LastEpoch,
		&i.Delta,
		&i.Freq,
		&i.Ndelta,
	)
	return i, err
}

const insertLastSeenSection = `-- name: InsertLastSeenSection :exec
INSERT INTO last_seen (section, class, cptr, first, last, delta, freq)
VALUES ($1, -1, -1, now(), now(), 0, 1)
`

func (q *Queries) InsertLastSeenSection(ctx context.Context, section *string) error {
	_, err := q.db.Exec(ctx, insertLastSeenSection, section)
	return err
}

const listLastSeen = `-- name: ListLastSeen :many
SELECT section, class, cptr,
       EXTRACT(EPOCH FROM first)::float8 AS first_epoch,
       EXTRACT(EPOCH FROM last)::float8 AS last_epoch,
       delta, freq,
       EXTRACT(EPOCH FROM (now() - last))::float8 AS ndelta
FROM last_seen
ORDER BY section
`

type ListLastSeenRow struct {
	Section    *string `json:"section"`
	Class      *int32  `json:"class"`
	Cptr       *int32  `json:"cptr"`
	FirstEpoch float64 `json:"first_epoch"`
	LastEpoch  float64 `json:"last_epoch"`
	Delta      float32 `json:"delta"`
	Freq       int32   `json:"freq"`
	Ndelta     float64 `json:"ndelta"`
}

func (q *Queries) ListLastSeen(ctx context.Context) ([]ListLastSeenRow, error) {
	rows, err := q.db.Query(ctx, listLastSeen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLastSeenRow{}
	for rows.Next() {
		var i ListLastSeenRow
		if err := rows.Scan(
			&i.Section,
			&i.Class,
			&i.Cptr,
			&i.FirstEpoch,
			&i.LastEpoch,
			&i.Delta,
			&i.Freq,
			&i.Ndelta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentNPtrs = `-- name: ListRecentNPtrs :many
SELECT class, cptr
FROM last_seen
WHERE last > now() - make_interval(hours => $1)
`

type ListRecentNPtrsRow struct {
	Class *int32 `json:"class"`
	Cptr  *int32 `json:"cptr"`
}

func (q *Queries) ListRecentNPtrs(ctx context.Context, hours int32) ([]ListRecentNPtrsRow, error) {
	rows, err := q.db.Query(ctx, listRecentNPtrs, hours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentNPtrsRow{}
	for rows.Next() {
		var i ListRecentNPtrsRow
		if err := rows.Scan(&i.Class, &i.Cptr); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
