// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Arrowdirectory struct {
	Staindex *int32  `json:"staindex"`
	Long     *string `json:"long"`
	Short    *string `json:"short"`
	Arrptr   int32   `json:"arrptr"`
}

type Arrowinverse struct {
	Plus  int32 `json:"plus"`
	Minus int32 `json:"minus"`
}

type Bookmark struct {
	Query    *string `json:"query"`
	Bookmark *string `json:"bookmark"`
}

type Contextdirectory struct {
	Context *string `json:"context"`
	Ctxptr  int32   `json:"ctxptr"`
}

type Lastseen struct {
	Section *string          `json:"section"`
	Nptr    interface{}      `json:"nptr"`
	First   pgtype.Timestamp `json:"first"`
	Last    pgtype.Timestamp `json:"last"`
	Delta   *float32         `json:"delta"`
	Freq    *int32           `json:"freq"`
}

type Node struct {
	Nptr     interface{}   `json:"nptr"`
	L        *int32        `json:"l"`
	S        *string       `json:"s"`
	Search   interface{}   `json:"search"`
	Unsearch interface{}   `json:"unsearch"`
	Chap     *string       `json:"chap"`
	Seq      *bool         `json:"seq"`
	Im3      []interface{} `json:"im3"`
	Im2      []interface{} `json:"im2"`
	Im1      []interface{} `json:"im1"`
	In0      []interface{} `json:"in0"`
	Il1      []interface{} `json:"il1"`
	Ic2      []interface{} `json:"ic2"`
	Ie3      []interface{} `json:"ie3"`
}

type Pagemap struct {
	Chap  *string       `json:"chap"`
	Alias *string       `json:"alias"`
	Ctx   *int32        `json:"ctx"`
	Line  *int32        `json:"line"`
	Path  []interface{} `json:"path"`
}
