// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type StType string

const (
	StTypeMExpress  StType = "m_express"
	StTypeMContains StType = "m_contains"
	StTypeMLeads    StType = "m_leads"
	StTypeNear      StType = "near"
	StTypePLeads    StType = "p_leads"
	StTypePContains StType = "p_contains"
	StTypePExpress  StType = "p_express"
)

func (e *StType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StType(s)
	case string:
		*e = StType(s)
	default:
		return fmt.Errorf("unsupported scan type for StType: %T", src)
	}
	return nil
}

type NullStType struct {
	StType StType `json:"st_type"`
	Valid  bool   `json:"valid"` // Valid is true if StType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStType) Scan(value interface{}) error {
	if value == nil {
		ns.StType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StType), nil
}

type ArrowDirectory struct {
	ArrPtr    int32  `json:"arr_ptr"`
	StaIndex  int32  `json:"sta_index"`
	LongName  string `json:"long_name"`
	ShortName string `json:"short_name"`
}

type ArrowInverse struct {
	Plus  int32 `json:"plus"`
	Minus int32 `json:"minus"`
}

type Bookmark struct {
	Bookmark string `json:"bookmark"`
	Query    string `json:"query"`
}

type ContextDirectory struct {
	CtxPtr  int32  `json:"ctx_ptr"`
	Context string `json:"context"`
}

type Edge struct {
	SrcClass int32   `json:"src_class"`
	SrcCptr  int32   `json:"src_cptr"`
	DstClass int32   `json:"dst_class"`
	DstCptr  int32   `json:"dst_cptr"`
	Arr      int32   `json:"arr"`
	Wgt      float32 `json:"wgt"`
	Ctx      int32   `json:"ctx"`
	St       StType  `json:"st"`
}

type LastSeen struct {
	Section *string            `json:"section"`
	Class   *int32             `json:"class"`
	Cptr    *int32             `json:"cptr"`
	First   pgtype.Timestamptz `json:"first"`
	Last    pgtype.Timestamptz `json:"last"`
	Delta   float32            `json:"delta"`
	Freq    int32              `json:"freq"`
}

type Node struct {
	Class    int32       `json:"class"`
	Cptr     int32       `json:"cptr"`
	L        int32       `json:"l"`
	S        string      `json:"s"`
	Search   interface{} `json:"search"`
	Unsearch interface{} `json:"unsearch"`
	Chap     string      `json:"chap"`
	Seq      bool        `json:"seq"`
}

type PageMap struct {
	Chap  string `json:"chap"`
	Alias string `json:"alias"`
	Ctx   int32  `json:"ctx"`
	Line  int32  `json:"line"`
	Path  []byte `json:"path"`
}
