// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nodes.sql

package sqlc

import (
	"context"
)

const alterNodeLogged = `-- name: AlterNodeLogged :exec
ALTER TABLE node SET LOGGED
`

func (q *Queries) AlterNodeLogged(ctx context.Context) error {
	_, err := q.db.Exec(ctx, alterNodeLogged)
	return err
}

const alterPageMapLogged = `-- name: AlterPageMapLogged :exec
ALTER TABLE pagemap SET LOGGED
`

func (q *Queries) AlterPageMapLogged(ctx context.Context) error {
	_, err := q.db.Exec(ctx, alterPageMapLogged)
	return err
}

const appendLinkIc2 = `-- name: AppendLinkIc2 :exec
UPDATE node
SET ic2 = array_append(ic2, ROW($3::int, $4::real, $5::int, ROW($6::int, $7::int)::nodeptr)::link)
WHERE (nptr).cptr = $1::int
  AND (nptr).chan = $2::int
  AND (ic2 IS NULL OR NOT ROW($3::int, $4::real, $5::int, ROW($6::int, $7::int)::nodeptr)::link = ANY (ic2))
`

type AppendLinkIc2Params struct {
	Column1 int32   `json:"column_1"`
	Column2 int32   `json:"column_2"`
	Column3 int32   `json:"column_3"`
	Column4 float32 `json:"column_4"`
	Column5 int32   `json:"column_5"`
	Column6 int32   `json:"column_6"`
	Column7 int32   `json:"column_7"`
}

func (q *Queries) AppendLinkIc2(ctx context.Context, arg AppendLinkIc2Params) error {
	_, err := q.db.Exec(ctx, appendLinkIc2,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	return err
}

const appendLinkIe3 = `-- name: AppendLinkIe3 :exec
UPDATE node
SET ie3 = array_append(ie3, ROW($3::int, $4::real, $5::int, ROW($6::int, $7::int)::nodeptr)::link)
WHERE (nptr).cptr = $1::int
  AND (nptr).chan = $2::int
  AND (ie3 IS NULL OR NOT ROW($3::int, $4::real, $5::int, ROW($6::int, $7::int)::nodeptr)::link = ANY (ie3))
`

type AppendLinkIe3Params struct {
	Column1 int32   `json:"column_1"`
	Column2 int32   `json:"column_2"`
	Column3 int32   `json:"column_3"`
	Column4 float32 `json:"column_4"`
	Column5 int32   `json:"column_5"`
	Column6 int32   `json:"column_6"`
	Column7 int32   `json:"column_7"`
}

func (q *Queries) AppendLinkIe3(ctx context.Context, arg AppendLinkIe3Params) error {
	_, err := q.db.Exec(ctx, appendLinkIe3,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	return err
}

const appendLinkIl1 = `-- name: AppendLinkIl1 :exec
UPDATE node
SET il1 = array_append(il1, ROW($3::int, $4::real, $5::int, ROW($6::int, $7::int)::nodeptr)::link)
WHERE (nptr).cptr = $1::int
  AND (nptr).chan = $2::int
  AND (il1 IS NULL OR NOT ROW($3::int, $4::real, $5::int, ROW($6::int, $7::int)::nodeptr)::link = ANY (il1))
`

type AppendLinkIl1Params struct {
	Column1 int32   `json:"column_1"`
	Column2 int32   `json:"column_2"`
	Column3 int32   `json:"column_3"`
	Column4 float32 `json:"column_4"`
	Column5 int32   `json:"column_5"`
	Column6 int32   `json:"column_6"`
	Column7 int32   `json:"column_7"`
}

func (q *Queries) AppendLinkIl1(ctx context.Context, arg AppendLinkIl1Params) error {
	_, err := q.db.Exec(ctx, appendLinkIl1,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	return err
}

const appendLinkIm1 = `-- name: AppendLinkIm1 :exec
UPDATE node
SET im1 = array_append(im1, ROW($3::int, $4::real, $5::int, ROW($6::int, $7::int)::nodeptr)::link)
WHERE (nptr).cptr = $1::int
  AND (nptr).chan = $2::int
  AND (im1 IS NULL OR NOT ROW($3::int, $4::real, $5::int, ROW($6::int, $7::int)::nodeptr)::link = ANY (im1))
`

type AppendLinkIm1Params struct {
	Column1 int32   `json:"column_1"`
	Column2 int32   `json:"column_2"`
	Column3 int32   `json:"column_3"`
	Column4 float32 `json:"column_4"`
	Column5 int32   `json:"column_5"`
	Column6 int32   `json:"column_6"`
	Column7 int32   `json:"column_7"`
}

func (q *Queries) AppendLinkIm1(ctx context.Context, arg AppendLinkIm1Params) error {
	_, err := q.db.Exec(ctx, appendLinkIm1,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	return err
}

const appendLinkIm2 = `-- name: AppendLinkIm2 :exec
UPDATE node
SET im2 = array_append(im2, ROW($3::int, $4::real, $5::int, ROW($6::int, $7::int)::nodeptr)::link)
WHERE (nptr).cptr = $1::int
  AND (nptr).chan = $2::int
  AND (im2 IS NULL OR NOT ROW($3::int, $4::real, $5::int, ROW($6::int, $7::int)::nodeptr)::link = ANY (im2))
`

type AppendLinkIm2Params struct {
	Column1 int32   `json:"column_1"`
	Column2 int32   `json:"column_2"`
	Column3 int32   `json:"column_3"`
	Column4 float32 `json:"column_4"`
	Column5 int32   `json:"column_5"`
	Column6 int32   `json:"column_6"`
	Column7 int32   `json:"column_7"`
}

func (q *Queries) AppendLinkIm2(ctx context.Context, arg AppendLinkIm2Params) error {
	_, err := q.db.Exec(ctx, appendLinkIm2,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	return err
}

const appendLinkIm3 = `-- name: AppendLinkIm3 :exec

UPDATE node
SET im3 = array_append(im3, ROW($3::int, $4::real, $5::int, ROW($6::int, $7::int)::nodeptr)::link)
WHERE (nptr).cptr = $1::int
  AND (nptr).chan = $2::int
  AND (im3 IS NULL OR NOT ROW($3::int, $4::real, $5::int, ROW($6::int, $7::int)::nodeptr)::link = ANY (im3))
`

type AppendLinkIm3Params struct {
	Column1 int32   `json:"column_1"`
	Column2 int32   `json:"column_2"`
	Column3 int32   `json:"column_3"`
	Column4 float32 `json:"column_4"`
	Column5 int32   `json:"column_5"`
	Column6 int32   `json:"column_6"`
	Column7 int32   `json:"column_7"`
}

// Append link into one ST channel (dynamic column avoided via separate queries).
func (q *Queries) AppendLinkIm3(ctx context.Context, arg AppendLinkIm3Params) error {
	_, err := q.db.Exec(ctx, appendLinkIm3,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	return err
}

const appendLinkIn0 = `-- name: AppendLinkIn0 :exec
UPDATE node
SET in0 = array_append(in0, ROW($3::int, $4::real, $5::int, ROW($6::int, $7::int)::nodeptr)::link)
WHERE (nptr).cptr = $1::int
  AND (nptr).chan = $2::int
  AND (in0 IS NULL OR NOT ROW($3::int, $4::real, $5::int, ROW($6::int, $7::int)::nodeptr)::link = ANY (in0))
`

type AppendLinkIn0Params struct {
	Column1 int32   `json:"column_1"`
	Column2 int32   `json:"column_2"`
	Column3 int32   `json:"column_3"`
	Column4 float32 `json:"column_4"`
	Column5 int32   `json:"column_5"`
	Column6 int32   `json:"column_6"`
	Column7 int32   `json:"column_7"`
}

func (q *Queries) AppendLinkIn0(ctx context.Context, arg AppendLinkIn0Params) error {
	_, err := q.db.Exec(ctx, appendLinkIn0,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	return err
}

const createContextIndex = `-- name: CreateContextIndex :exec
CREATE INDEX IF NOT EXISTS sst_cnt ON contextdirectory USING gin (context)
`

func (q *Queries) CreateContextIndex(ctx context.Context) error {
	_, err := q.db.Exec(ctx, createContextIndex)
	return err
}

const createNodeIndexes = `-- name: CreateNodeIndexes :exec
CREATE INDEX IF NOT EXISTS sst_gin ON node USING gin (to_tsvector('english', search))
`

func (q *Queries) CreateNodeIndexes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, createNodeIndexes)
	return err
}

const createNodeIndexes2 = `-- name: CreateNodeIndexes2 :exec
CREATE INDEX IF NOT EXISTS sst_ungin ON node USING gin (to_tsvector('english', unsearch))
`

func (q *Queries) CreateNodeIndexes2(ctx context.Context) error {
	_, err := q.db.Exec(ctx, createNodeIndexes2)
	return err
}

const createNodeIndexes3 = `-- name: CreateNodeIndexes3 :exec
CREATE INDEX IF NOT EXISTS sst_s ON node USING gin (s)
`

func (q *Queries) CreateNodeIndexes3(ctx context.Context) error {
	_, err := q.db.Exec(ctx, createNodeIndexes3)
	return err
}

const createNodeIndexes4 = `-- name: CreateNodeIndexes4 :exec
CREATE INDEX IF NOT EXISTS sst_n ON node USING gin (nptr)
`

func (q *Queries) CreateNodeIndexes4(ctx context.Context) error {
	_, err := q.db.Exec(ctx, createNodeIndexes4)
	return err
}

const getNodeByNPtr = `-- name: GetNodeByNPtr :one
SELECT l,
       s,
       chap,
       im3::text AS im3,
       im2::text AS im2,
       im1::text AS im1,
       in0::text AS in0,
       il1::text AS il1,
       ic2::text AS ic2,
       ie3::text AS ie3
FROM node
WHERE nptr = ROW($1::int, $2::int)::nodeptr
  AND NOT l = 0
`

type GetNodeByNPtrParams struct {
	Column1 int32 `json:"column_1"`
	Column2 int32 `json:"column_2"`
}

type GetNodeByNPtrRow struct {
	L    *int32  `json:"l"`
	S    *string `json:"s"`
	Chap *string `json:"chap"`
	Im3  string  `json:"im3"`
	Im2  string  `json:"im2"`
	Im1  string  `json:"im1"`
	In0  string  `json:"in0"`
	Il1  string  `json:"il1"`
	Ic2  string  `json:"ic2"`
	Ie3  string  `json:"ie3"`
}

func (q *Queries) GetNodeByNPtr(ctx context.Context, arg GetNodeByNPtrParams) (GetNodeByNPtrRow, error) {
	row := q.db.QueryRow(ctx, getNodeByNPtr, arg.Column1, arg.Column2)
	var i GetNodeByNPtrRow
	err := row.Scan(
		&i.L,
		&i.S,
		&i.Chap,
		&i.Im3,
		&i.Im2,
		&i.Im1,
		&i.In0,
		&i.Il1,
		&i.Ic2,
		&i.Ie3,
	)
	return i, err
}

const idempAppendNode = `-- name: IdempAppendNode :one
SELECT r.ret_cptr::int AS chan, r.ret_channel::int AS cptr
FROM idempappendnode($1::int, $2::int, $3, $4) AS r
`

type IdempAppendNodeParams struct {
	Column1 int32  `json:"column_1"`
	Column2 int32  `json:"column_2"`
	Isi     string `json:"isi"`
	Ichapi  string `json:"ichapi"`
}

type IdempAppendNodeRow struct {
	Chan int32 `json:"chan"`
	Cptr int32 `json:"cptr"`
}

// Body fills ret_cptr/ret_channel from (Chan, CPtr) respectively.
func (q *Queries) IdempAppendNode(ctx context.Context, arg IdempAppendNodeParams) (IdempAppendNodeRow, error) {
	row := q.db.QueryRow(ctx, idempAppendNode,
		arg.Column1,
		arg.Column2,
		arg.Isi,
		arg.Ichapi,
	)
	var i IdempAppendNodeRow
	err := row.Scan(&i.Chan, &i.Cptr)
	return i, err
}

const insertNodeFn = `-- name: InsertNodeFn :exec
SELECT insertnode($1::int, $2::int, $3::int, $4, $5, $6::boolean)
`

type InsertNodeFnParams struct {
	Column1 int32  `json:"column_1"`
	Column2 int32  `json:"column_2"`
	Column3 int32  `json:"column_3"`
	Isi     string `json:"isi"`
	Ichapi  string `json:"ichapi"`
	Column6 bool   `json:"column_6"`
}

func (q *Queries) InsertNodeFn(ctx context.Context, arg InsertNodeFnParams) error {
	_, err := q.db.Exec(ctx, insertNodeFn,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Isi,
		arg.Ichapi,
		arg.Column6,
	)
	return err
}

const insertNodeRow = `-- name: InsertNodeRow :exec
INSERT INTO node (nptr, l, s, chap, seq, im3, im2, im1, in0, il1, ic2, ie3)
VALUES (
  ROW($1::int, $2::int)::nodeptr,
  $3::int,
  $4,
  $5,
  $6::boolean,
  COALESCE($7::text::link[], '{}'::link[]),
  COALESCE($8::text::link[], '{}'::link[]),
  COALESCE($9::text::link[], '{}'::link[]),
  COALESCE($10::text::link[], '{}'::link[]),
  COALESCE($11::text::link[], '{}'::link[]),
  COALESCE($12::text::link[], '{}'::link[]),
  COALESCE($13::text::link[], '{}'::link[])
)
`

type InsertNodeRowParams struct {
	Column1  int32   `json:"column_1"`
	Column2  int32   `json:"column_2"`
	Column3  int32   `json:"column_3"`
	S        *string `json:"s"`
	Chap     *string `json:"chap"`
	Column6  bool    `json:"column_6"`
	Column7  string  `json:"column_7"`
	Column8  string  `json:"column_8"`
	Column9  string  `json:"column_9"`
	Column10 string  `json:"column_10"`
	Column11 string  `json:"column_11"`
	Column12 string  `json:"column_12"`
	Column13 string  `json:"column_13"`
}

func (q *Queries) InsertNodeRow(ctx context.Context, arg InsertNodeRowParams) error {
	_, err := q.db.Exec(ctx, insertNodeRow,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.S,
		arg.Chap,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Column11,
		arg.Column12,
		arg.Column13,
	)
	return err
}

const listAdjacentNodes = `-- name: ListAdjacentNodes :many

SELECT (nptr).chan::int AS chan,
       (nptr).cptr::int AS cptr,
       im3::text AS im3,
       im2::text AS im2,
       im1::text AS im1,
       in0::text AS in0,
       il1::text AS il1,
       ic2::text AS ic2,
       ie3::text AS ie3
FROM node
WHERE lower(chap) LIKE lower($1)
  AND (
    ($2::boolean AND array_length(im3::text[], 1) IS NOT NULL
      AND match_context((im3)[0].ctx, COALESCE($9::text[], ARRAY[]::text[])))
    OR ($3::boolean AND array_length(im2::text[], 1) IS NOT NULL
      AND match_context((im2)[0].ctx, COALESCE($9::text[], ARRAY[]::text[])))
    OR ($4::boolean AND array_length(im1::text[], 1) IS NOT NULL
      AND match_context((im1)[0].ctx, COALESCE($9::text[], ARRAY[]::text[])))
    OR ($5::boolean AND array_length(in0::text[], 1) IS NOT NULL
      AND match_context((in0)[0].ctx, COALESCE($9::text[], ARRAY[]::text[])))
    OR ($6::boolean AND array_length(il1::text[], 1) IS NOT NULL
      AND match_context((il1)[0].ctx, COALESCE($9::text[], ARRAY[]::text[])))
    OR ($7::boolean AND array_length(ic2::text[], 1) IS NOT NULL
      AND match_context((ic2)[0].ctx, COALESCE($9::text[], ARRAY[]::text[])))
    OR ($8::boolean AND array_length(ie3::text[], 1) IS NOT NULL
      AND match_context((ie3)[0].ctx, COALESCE($9::text[], ARRAY[]::text[])))
  )
`

type ListAdjacentNodesParams struct {
	Lower   string   `json:"lower"`
	Column2 bool     `json:"column_2"`
	Column3 bool     `json:"column_3"`
	Column4 bool     `json:"column_4"`
	Column5 bool     `json:"column_5"`
	Column6 bool     `json:"column_6"`
	Column7 bool     `json:"column_7"`
	Column8 bool     `json:"column_8"`
	Column9 []string `json:"column_9"`
}

type ListAdjacentNodesRow struct {
	Chan int32  `json:"chan"`
	Cptr int32  `json:"cptr"`
	Im3  string `json:"im3"`
	Im2  string `json:"im2"`
	Im1  string `json:"im1"`
	In0  string `json:"in0"`
	Il1  string `json:"il1"`
	Ic2  string `json:"ic2"`
	Ie3  string `json:"ie3"`
}

// Adjacency: always return all link channels as text; Go picks which ST types matter.
func (q *Queries) ListAdjacentNodes(ctx context.Context, arg ListAdjacentNodesParams) ([]ListAdjacentNodesRow, error) {
	rows, err := q.db.Query(ctx, listAdjacentNodes,
		arg.Lower,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdjacentNodesRow{}
	for rows.Next() {
		var i ListAdjacentNodesRow
		if err := rows.Scan(
			&i.Chan,
			&i.Cptr,
			&i.Im3,
			&i.Im2,
			&i.Im1,
			&i.In0,
			&i.Il1,
			&i.Ic2,
			&i.Ie3,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChaptersLike = `-- name: ListChaptersLike :many
SELECT DISTINCT chap
FROM node
WHERE lower(chap) LIKE lower($1)
ORDER BY chap
`

func (q *Queries) ListChaptersLike(ctx context.Context, lower string) ([]*string, error) {
	rows, err := q.db.Query(ctx, listChaptersLike, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var chap *string
		if err := rows.Scan(&chap); err != nil {
			return nil, err
		}
		items = append(items, chap)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChaptersLikeUnaccent = `-- name: ListChaptersLikeUnaccent :many
SELECT DISTINCT chap
FROM node
WHERE lower(unaccent(chap)) LIKE lower($1)
ORDER BY chap
`

func (q *Queries) ListChaptersLikeUnaccent(ctx context.Context, lower string) ([]*string, error) {
	rows, err := q.db.Query(ctx, listChaptersLikeUnaccent, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var chap *string
		if err := rows.Scan(&chap); err != nil {
			return nil, err
		}
		items = append(items, chap)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSingletonSinks = `-- name: ListSingletonSinks :many
SELECT (nptr).chan::int AS chan, (nptr).cptr::int AS cptr
FROM node
WHERE lower(chap) LIKE lower($1)
  AND (
    ($2::boolean AND array_length(im1::text[], 1) IS NOT NULL AND array_length(il1::text[], 1) IS NULL
      AND match_context((im1)[0].ctx, COALESCE($6::text[], ARRAY[]::text[])))
    OR ($3::boolean AND array_length(im2::text[], 1) IS NOT NULL AND array_length(ic2::text[], 1) IS NULL
      AND match_context((im2)[0].ctx, COALESCE($6::text[], ARRAY[]::text[])))
    OR ($4::boolean AND array_length(im3::text[], 1) IS NOT NULL AND array_length(ie3::text[], 1) IS NULL
      AND match_context((im3)[0].ctx, COALESCE($6::text[], ARRAY[]::text[])))
    OR ($5::boolean AND array_length(in0::text[], 1) IS NOT NULL
      AND match_context((in0)[0].ctx, COALESCE($6::text[], ARRAY[]::text[])))
  )
`

type ListSingletonSinksParams struct {
	Lower   string   `json:"lower"`
	Column2 bool     `json:"column_2"`
	Column3 bool     `json:"column_3"`
	Column4 bool     `json:"column_4"`
	Column5 bool     `json:"column_5"`
	Column6 []string `json:"column_6"`
}

type ListSingletonSinksRow struct {
	Chan int32 `json:"chan"`
	Cptr int32 `json:"cptr"`
}

func (q *Queries) ListSingletonSinks(ctx context.Context, arg ListSingletonSinksParams) ([]ListSingletonSinksRow, error) {
	rows, err := q.db.Query(ctx, listSingletonSinks,
		arg.Lower,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSingletonSinksRow{}
	for rows.Next() {
		var i ListSingletonSinksRow
		if err := rows.Scan(&i.Chan, &i.Cptr); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSingletonSources = `-- name: ListSingletonSources :many

SELECT (nptr).chan::int AS chan, (nptr).cptr::int AS cptr
FROM node
WHERE lower(chap) LIKE lower($1)
  AND (
    ($2::boolean AND array_length(il1::text[], 1) IS NOT NULL AND array_length(im1::text[], 1) IS NULL
      AND match_context((il1)[0].ctx, COALESCE($6::text[], ARRAY[]::text[])))
    OR ($3::boolean AND array_length(ic2::text[], 1) IS NOT NULL AND array_length(im2::text[], 1) IS NULL
      AND match_context((ic2)[0].ctx, COALESCE($6::text[], ARRAY[]::text[])))
    OR ($4::boolean AND array_length(ie3::text[], 1) IS NOT NULL AND array_length(im3::text[], 1) IS NULL
      AND match_context((ie3)[0].ctx, COALESCE($6::text[], ARRAY[]::text[])))
    OR ($5::boolean AND array_length(in0::text[], 1) IS NOT NULL
      AND match_context((in0)[0].ctx, COALESCE($6::text[], ARRAY[]::text[])))
  )
`

type ListSingletonSourcesParams struct {
	Lower   string   `json:"lower"`
	Column2 bool     `json:"column_2"`
	Column3 bool     `json:"column_3"`
	Column4 bool     `json:"column_4"`
	Column5 bool     `json:"column_5"`
	Column6 []string `json:"column_6"`
}

type ListSingletonSourcesRow struct {
	Chan int32 `json:"chan"`
	Cptr int32 `json:"cptr"`
}

// Singleton sources/sinks: flags enable each ST channel (positive ST = out).
func (q *Queries) ListSingletonSources(ctx context.Context, arg ListSingletonSourcesParams) ([]ListSingletonSourcesRow, error) {
	rows, err := q.db.Query(ctx, listSingletonSources,
		arg.Lower,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSingletonSourcesRow{}
	for rows.Next() {
		var i ListSingletonSourcesRow
		if err := rows.Scan(&i.Chan, &i.Cptr); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxCPtrForChan = `-- name: MaxCPtrForChan :one
SELECT COALESCE(max((nptr).cptr), -1)::int AS max_cptr
FROM node
WHERE (nptr).chan = $1::int
`

func (q *Queries) MaxCPtrForChan(ctx context.Context, dollar_1 int32) (int32, error) {
	row := q.db.QueryRow(ctx, maxCPtrForChan, dollar_1)
	var max_cptr int32
	err := row.Scan(&max_cptr)
	return max_cptr, err
}

const searchNodePtrs = `-- name: SearchNodePtrs :many
SELECT (nptr).chan::int AS chan, (nptr).cptr::int AS cptr
FROM node
WHERE
  CASE
    WHEN $1::boolean THEN true
    WHEN $2::boolean THEN lower(unaccent(chap)) LIKE lower($3)
    ELSE lower(chap) LIKE lower($3)
  END
  AND CASE $4::text
    WHEN 'any' THEN true
    WHEN 'exact' THEN lower(s) = lower($5)
    WHEN 'like' THEN lower(s) LIKE lower($5)
    WHEN 'fts' THEN search @@ to_tsquery('english', $5)
    WHEN 'ufts' THEN unsearch @@ to_tsquery('english', $5)
    ELSE true
  END
  AND (NOT $6::boolean OR s NOT LIKE '/%')
  AND (NOT $7::boolean OR seq = true)
  AND ncc_match(
    nptr,
    COALESCE($8::text[], ARRAY[]::text[]),
    COALESCE($9::int[], ARRAY[]::int[]),
    COALESCE($10::int[], ARRAY[]::int[]),
    im3, im2, im1, in0, il1, ic2, ie3
  )
ORDER BY s ASC, (cardinality(ie3) + cardinality(im3) + cardinality(il1)) DESC
LIMIT $11
`

type SearchNodePtrsParams struct {
	Column1  bool     `json:"column_1"`
	Column2  bool     `json:"column_2"`
	Lower    string   `json:"lower"`
	Column4  string   `json:"column_4"`
	Lower_2  string   `json:"lower_2"`
	Column6  bool     `json:"column_6"`
	Column7  bool     `json:"column_7"`
	Column8  []string `json:"column_8"`
	Column9  []int32  `json:"column_9"`
	Column10 []int32  `json:"column_10"`
	Limit    int32    `json:"limit"`
}

type SearchNodePtrsRow struct {
	Chan int32 `json:"chan"`
	Cptr int32 `json:"cptr"`
}

// $1 any_chapter, $2 chap_unaccent, $3 chap_pattern
// $4 name_mode: any|exact|like|fts|ufts, $5 name_arg
// $6 exclude_paths, $7 seq_only
// $8 context text[], $9 arrows int[], $10 sttypes int[], $11 limit
func (q *Queries) SearchNodePtrs(ctx context.Context, arg SearchNodePtrsParams) ([]SearchNodePtrsRow, error) {
	rows, err := q.db.Query(ctx, searchNodePtrs,
		arg.Column1,
		arg.Column2,
		arg.Lower,
		arg.Column4,
		arg.Lower_2,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchNodePtrsRow{}
	for rows.Next() {
		var i SearchNodePtrsRow
		if err := rows.Scan(&i.Chan, &i.Cptr); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLinkArrayIc2 = `-- name: SetLinkArrayIc2 :exec
UPDATE node SET ic2 = $3::text::link[] WHERE (nptr).cptr = $1::int AND (nptr).chan = $2::int
`

type SetLinkArrayIc2Params struct {
	Column1 int32  `json:"column_1"`
	Column2 int32  `json:"column_2"`
	Column3 string `json:"column_3"`
}

func (q *Queries) SetLinkArrayIc2(ctx context.Context, arg SetLinkArrayIc2Params) error {
	_, err := q.db.Exec(ctx, setLinkArrayIc2, arg.Column1, arg.Column2, arg.Column3)
	return err
}

const setLinkArrayIe3 = `-- name: SetLinkArrayIe3 :exec
UPDATE node SET ie3 = $3::text::link[] WHERE (nptr).cptr = $1::int AND (nptr).chan = $2::int
`

type SetLinkArrayIe3Params struct {
	Column1 int32  `json:"column_1"`
	Column2 int32  `json:"column_2"`
	Column3 string `json:"column_3"`
}

func (q *Queries) SetLinkArrayIe3(ctx context.Context, arg SetLinkArrayIe3Params) error {
	_, err := q.db.Exec(ctx, setLinkArrayIe3, arg.Column1, arg.Column2, arg.Column3)
	return err
}

const setLinkArrayIl1 = `-- name: SetLinkArrayIl1 :exec
UPDATE node SET il1 = $3::text::link[] WHERE (nptr).cptr = $1::int AND (nptr).chan = $2::int
`

type SetLinkArrayIl1Params struct {
	Column1 int32  `json:"column_1"`
	Column2 int32  `json:"column_2"`
	Column3 string `json:"column_3"`
}

func (q *Queries) SetLinkArrayIl1(ctx context.Context, arg SetLinkArrayIl1Params) error {
	_, err := q.db.Exec(ctx, setLinkArrayIl1, arg.Column1, arg.Column2, arg.Column3)
	return err
}

const setLinkArrayIm1 = `-- name: SetLinkArrayIm1 :exec
UPDATE node SET im1 = $3::text::link[] WHERE (nptr).cptr = $1::int AND (nptr).chan = $2::int
`

type SetLinkArrayIm1Params struct {
	Column1 int32  `json:"column_1"`
	Column2 int32  `json:"column_2"`
	Column3 string `json:"column_3"`
}

func (q *Queries) SetLinkArrayIm1(ctx context.Context, arg SetLinkArrayIm1Params) error {
	_, err := q.db.Exec(ctx, setLinkArrayIm1, arg.Column1, arg.Column2, arg.Column3)
	return err
}

const setLinkArrayIm2 = `-- name: SetLinkArrayIm2 :exec
UPDATE node SET im2 = $3::text::link[] WHERE (nptr).cptr = $1::int AND (nptr).chan = $2::int
`

type SetLinkArrayIm2Params struct {
	Column1 int32  `json:"column_1"`
	Column2 int32  `json:"column_2"`
	Column3 string `json:"column_3"`
}

func (q *Queries) SetLinkArrayIm2(ctx context.Context, arg SetLinkArrayIm2Params) error {
	_, err := q.db.Exec(ctx, setLinkArrayIm2, arg.Column1, arg.Column2, arg.Column3)
	return err
}

const setLinkArrayIm3 = `-- name: SetLinkArrayIm3 :exec
UPDATE node SET im3 = $3::text::link[] WHERE (nptr).cptr = $1::int AND (nptr).chan = $2::int
`

type SetLinkArrayIm3Params struct {
	Column1 int32  `json:"column_1"`
	Column2 int32  `json:"column_2"`
	Column3 string `json:"column_3"`
}

func (q *Queries) SetLinkArrayIm3(ctx context.Context, arg SetLinkArrayIm3Params) error {
	_, err := q.db.Exec(ctx, setLinkArrayIm3, arg.Column1, arg.Column2, arg.Column3)
	return err
}

const setLinkArrayIn0 = `-- name: SetLinkArrayIn0 :exec
UPDATE node SET in0 = $3::text::link[] WHERE (nptr).cptr = $1::int AND (nptr).chan = $2::int
`

type SetLinkArrayIn0Params struct {
	Column1 int32  `json:"column_1"`
	Column2 int32  `json:"column_2"`
	Column3 string `json:"column_3"`
}

func (q *Queries) SetLinkArrayIn0(ctx context.Context, arg SetLinkArrayIn0Params) error {
	_, err := q.db.Exec(ctx, setLinkArrayIn0, arg.Column1, arg.Column2, arg.Column3)
	return err
}

const truncateAllData = `-- name: TruncateAllData :exec
TRUNCATE TABLE
  node, pagemap, bookmarks, lastseen,
  arrowdirectory, arrowinverses, contextdirectory
CASCADE
`

func (q *Queries) TruncateAllData(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateAllData)
	return err
}
