// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nodes.sql

package sqlc

import (
	"context"
)

const deleteNodesByChapter = `-- name: DeleteNodesByChapter :exec
DELETE FROM node
WHERE chap = $1
`

func (q *Queries) DeleteNodesByChapter(ctx context.Context, chap string) error {
	_, err := q.db.Exec(ctx, deleteNodesByChapter, chap)
	return err
}

const getNodeByPtr = `-- name: GetNodeByPtr :one
SELECT class, cptr, l, s, chap, seq
FROM node
WHERE class = $1 AND cptr = $2
`

type GetNodeByPtrParams struct {
	Class int32 `json:"class"`
	Cptr  int32 `json:"cptr"`
}

type GetNodeByPtrRow struct {
	Class int32  `json:"class"`
	Cptr  int32  `json:"cptr"`
	L     int32  `json:"l"`
	S     string `json:"s"`
	Chap  string `json:"chap"`
	Seq   bool   `json:"seq"`
}

func (q *Queries) GetNodeByPtr(ctx context.Context, arg GetNodeByPtrParams) (GetNodeByPtrRow, error) {
	row := q.db.QueryRow(ctx, getNodeByPtr, arg.Class, arg.Cptr)
	var i GetNodeByPtrRow
	err := row.Scan(
		&i.Class,
		&i.Cptr,
		&i.L,
		&i.S,
		&i.Chap,
		&i.Seq,
	)
	return i, err
}

const getNodeByText = `-- name: GetNodeByText :one
SELECT class, cptr, l, s, chap, seq
FROM node
WHERE lower(s) = lower($1)
LIMIT 1
`

type GetNodeByTextRow struct {
	Class int32  `json:"class"`
	Cptr  int32  `json:"cptr"`
	L     int32  `json:"l"`
	S     string `json:"s"`
	Chap  string `json:"chap"`
	Seq   bool   `json:"seq"`
}

func (q *Queries) GetNodeByText(ctx context.Context, lower string) (GetNodeByTextRow, error) {
	row := q.db.QueryRow(ctx, getNodeByText, lower)
	var i GetNodeByTextRow
	err := row.Scan(
		&i.Class,
		&i.Cptr,
		&i.L,
		&i.S,
		&i.Chap,
		&i.Seq,
	)
	return i, err
}

const insertNode = `-- name: InsertNode :exec
INSERT INTO node (class, cptr, l, s, chap, seq)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertNodeParams struct {
	Class int32  `json:"class"`
	Cptr  int32  `json:"cptr"`
	L     int32  `json:"l"`
	S     string `json:"s"`
	Chap  string `json:"chap"`
	Seq   bool   `json:"seq"`
}

func (q *Queries) InsertNode(ctx context.Context, arg InsertNodeParams) error {
	_, err := q.db.Exec(ctx, insertNode,
		arg.Class,
		arg.Cptr,
		arg.L,
		arg.S,
		arg.Chap,
		arg.Seq,
	)
	return err
}

const listChaptersLike = `-- name: ListChaptersLike :many
SELECT DISTINCT chap
FROM node
WHERE lower(chap) LIKE lower($1)
ORDER BY chap
`

func (q *Queries) ListChaptersLike(ctx context.Context, lower string) ([]string, error) {
	rows, err := q.db.Query(ctx, listChaptersLike, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var chap string
		if err := rows.Scan(&chap); err != nil {
			return nil, err
		}
		items = append(items, chap)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChaptersLikeUnaccent = `-- name: ListChaptersLikeUnaccent :many
SELECT DISTINCT chap
FROM node
WHERE lower(unaccent(chap)) LIKE lower($1)
ORDER BY chap
`

func (q *Queries) ListChaptersLikeUnaccent(ctx context.Context, lower string) ([]string, error) {
	rows, err := q.db.Query(ctx, listChaptersLikeUnaccent, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var chap string
		if err := rows.Scan(&chap); err != nil {
			return nil, err
		}
		items = append(items, chap)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxCPtrForClass = `-- name: MaxCPtrForClass :one
SELECT COALESCE(max(cptr), -1)::int AS max_cptr
FROM node
WHERE class = $1
`

func (q *Queries) MaxCPtrForClass(ctx context.Context, class int32) (int32, error) {
	row := q.db.QueryRow(ctx, maxCPtrForClass, class)
	var max_cptr int32
	err := row.Scan(&max_cptr)
	return max_cptr, err
}

const searchNodesExact = `-- name: SearchNodesExact :many
SELECT class, cptr, l, s, chap, seq
FROM node
WHERE lower(s) = lower($1)
ORDER BY s ASC
LIMIT $2
`

type SearchNodesExactParams struct {
	Lower string `json:"lower"`
	Limit int32  `json:"limit"`
}

type SearchNodesExactRow struct {
	Class int32  `json:"class"`
	Cptr  int32  `json:"cptr"`
	L     int32  `json:"l"`
	S     string `json:"s"`
	Chap  string `json:"chap"`
	Seq   bool   `json:"seq"`
}

func (q *Queries) SearchNodesExact(ctx context.Context, arg SearchNodesExactParams) ([]SearchNodesExactRow, error) {
	rows, err := q.db.Query(ctx, searchNodesExact, arg.Lower, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchNodesExactRow{}
	for rows.Next() {
		var i SearchNodesExactRow
		if err := rows.Scan(
			&i.Class,
			&i.Cptr,
			&i.L,
			&i.S,
			&i.Chap,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNodesLike = `-- name: SearchNodesLike :many
SELECT class, cptr, l, s, chap, seq
FROM node
WHERE lower(s) LIKE lower($1)
ORDER BY s ASC
LIMIT $2
`

type SearchNodesLikeParams struct {
	Lower string `json:"lower"`
	Limit int32  `json:"limit"`
}

type SearchNodesLikeRow struct {
	Class int32  `json:"class"`
	Cptr  int32  `json:"cptr"`
	L     int32  `json:"l"`
	S     string `json:"s"`
	Chap  string `json:"chap"`
	Seq   bool   `json:"seq"`
}

func (q *Queries) SearchNodesLike(ctx context.Context, arg SearchNodesLikeParams) ([]SearchNodesLikeRow, error) {
	rows, err := q.db.Query(ctx, searchNodesLike, arg.Lower, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchNodesLikeRow{}
	for rows.Next() {
		var i SearchNodesLikeRow
		if err := rows.Scan(
			&i.Class,
			&i.Cptr,
			&i.L,
			&i.S,
			&i.Chap,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNodesTsquery = `-- name: SearchNodesTsquery :many
SELECT class, cptr, l, s, chap, seq
FROM node
WHERE search @@ to_tsquery('english', $1)
ORDER BY s ASC
LIMIT $2
`

type SearchNodesTsqueryParams struct {
	ToTsquery string `json:"to_tsquery"`
	Limit     int32  `json:"limit"`
}

type SearchNodesTsqueryRow struct {
	Class int32  `json:"class"`
	Cptr  int32  `json:"cptr"`
	L     int32  `json:"l"`
	S     string `json:"s"`
	Chap  string `json:"chap"`
	Seq   bool   `json:"seq"`
}

func (q *Queries) SearchNodesTsquery(ctx context.Context, arg SearchNodesTsqueryParams) ([]SearchNodesTsqueryRow, error) {
	rows, err := q.db.Query(ctx, searchNodesTsquery, arg.ToTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchNodesTsqueryRow{}
	for rows.Next() {
		var i SearchNodesTsqueryRow
		if err := rows.Scan(
			&i.Class,
			&i.Cptr,
			&i.L,
			&i.S,
			&i.Chap,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNodesTsqueryUnaccent = `-- name: SearchNodesTsqueryUnaccent :many
SELECT class, cptr, l, s, chap, seq
FROM node
WHERE unsearch @@ to_tsquery('english', $1)
ORDER BY s ASC
LIMIT $2
`

type SearchNodesTsqueryUnaccentParams struct {
	ToTsquery string `json:"to_tsquery"`
	Limit     int32  `json:"limit"`
}

type SearchNodesTsqueryUnaccentRow struct {
	Class int32  `json:"class"`
	Cptr  int32  `json:"cptr"`
	L     int32  `json:"l"`
	S     string `json:"s"`
	Chap  string `json:"chap"`
	Seq   bool   `json:"seq"`
}

func (q *Queries) SearchNodesTsqueryUnaccent(ctx context.Context, arg SearchNodesTsqueryUnaccentParams) ([]SearchNodesTsqueryUnaccentRow, error) {
	rows, err := q.db.Query(ctx, searchNodesTsqueryUnaccent, arg.ToTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchNodesTsqueryUnaccentRow{}
	for rows.Next() {
		var i SearchNodesTsqueryUnaccentRow
		if err := rows.Scan(
			&i.Class,
			&i.Cptr,
			&i.L,
			&i.S,
			&i.Chap,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNodeChapter = `-- name: UpdateNodeChapter :exec
UPDATE node
SET chap = $3
WHERE class = $1 AND cptr = $2
`

type UpdateNodeChapterParams struct {
	Class int32  `json:"class"`
	Cptr  int32  `json:"cptr"`
	Chap  string `json:"chap"`
}

func (q *Queries) UpdateNodeChapter(ctx context.Context, arg UpdateNodeChapterParams) error {
	_, err := q.db.Exec(ctx, updateNodeChapter, arg.Class, arg.Cptr, arg.Chap)
	return err
}

const updateNodeSeq = `-- name: UpdateNodeSeq :exec
UPDATE node
SET seq = $3
WHERE class = $1 AND cptr = $2
`

type UpdateNodeSeqParams struct {
	Class int32 `json:"class"`
	Cptr  int32 `json:"cptr"`
	Seq   bool  `json:"seq"`
}

func (q *Queries) UpdateNodeSeq(ctx context.Context, arg UpdateNodeSeqParams) error {
	_, err := q.db.Exec(ctx, updateNodeSeq, arg.Class, arg.Cptr, arg.Seq)
	return err
}
