// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nodes.sql

package sqlc

import (
	"context"
)

const listChaptersLike = `-- name: ListChaptersLike :many
SELECT DISTINCT chap
FROM node
WHERE lower(chap) LIKE lower($1)
ORDER BY chap
`

func (q *Queries) ListChaptersLike(ctx context.Context, lower string) ([]*string, error) {
	rows, err := q.db.Query(ctx, listChaptersLike, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var chap *string
		if err := rows.Scan(&chap); err != nil {
			return nil, err
		}
		items = append(items, chap)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChaptersLikeUnaccent = `-- name: ListChaptersLikeUnaccent :many
SELECT DISTINCT chap
FROM node
WHERE lower(unaccent(chap)) LIKE lower($1)
ORDER BY chap
`

func (q *Queries) ListChaptersLikeUnaccent(ctx context.Context, lower string) ([]*string, error) {
	rows, err := q.db.Query(ctx, listChaptersLikeUnaccent, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var chap *string
		if err := rows.Scan(&chap); err != nil {
			return nil, err
		}
		items = append(items, chap)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxCPtrForChan = `-- name: MaxCPtrForChan :one
SELECT COALESCE(max((nptr).cptr), -1)::int AS max_cptr
FROM node
WHERE (nptr).chan = $1
`

func (q *Queries) MaxCPtrForChan(ctx context.Context, nptr interface{}) (int32, error) {
	row := q.db.QueryRow(ctx, maxCPtrForChan, nptr)
	var max_cptr int32
	err := row.Scan(&max_cptr)
	return max_cptr, err
}

const truncateAllData = `-- name: TruncateAllData :exec
TRUNCATE TABLE
  node, pagemap, bookmarks, lastseen,
  arrowdirectory, arrowinverses, contextdirectory
CASCADE
`

func (q *Queries) TruncateAllData(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateAllData)
	return err
}
