// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pagemap.sql

package sqlc

import (
	"context"
)

const insertPageMap = `-- name: InsertPageMap :exec
INSERT INTO page_map (chap, alias, ctx, line, path)
VALUES ($1, $2, $3, $4, $5)
`

type InsertPageMapParams struct {
	Chap  string `json:"chap"`
	Alias string `json:"alias"`
	Ctx   int32  `json:"ctx"`
	Line  int32  `json:"line"`
	Path  []byte `json:"path"`
}

func (q *Queries) InsertPageMap(ctx context.Context, arg InsertPageMapParams) error {
	_, err := q.db.Exec(ctx, insertPageMap,
		arg.Chap,
		arg.Alias,
		arg.Ctx,
		arg.Line,
		arg.Path,
	)
	return err
}

const listPageMapByContext = `-- name: ListPageMapByContext :many
SELECT chap, alias, ctx, line, path
FROM page_map
WHERE match_context(ctx, $1::text[])
ORDER BY chap, line
`

func (q *Queries) ListPageMapByContext(ctx context.Context, dollar_1 []string) ([]PageMap, error) {
	rows, err := q.db.Query(ctx, listPageMapByContext, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PageMap{}
	for rows.Next() {
		var i PageMap
		if err := rows.Scan(
			&i.Chap,
			&i.Alias,
			&i.Ctx,
			&i.Line,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPageMapDistinctChapCtx = `-- name: ListPageMapDistinctChapCtx :many
SELECT DISTINCT chap, ctx
FROM page_map
WHERE match_context(ctx, $1::text[])
ORDER BY chap
`

type ListPageMapDistinctChapCtxRow struct {
	Chap string `json:"chap"`
	Ctx  int32  `json:"ctx"`
}

func (q *Queries) ListPageMapDistinctChapCtx(ctx context.Context, dollar_1 []string) ([]ListPageMapDistinctChapCtxRow, error) {
	rows, err := q.db.Query(ctx, listPageMapDistinctChapCtx, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPageMapDistinctChapCtxRow{}
	for rows.Next() {
		var i ListPageMapDistinctChapCtxRow
		if err := rows.Scan(&i.Chap, &i.Ctx); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
