// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pagemap.sql

package sqlc

import (
	"context"
)

const insertPageMap = `-- name: InsertPageMap :exec
INSERT INTO pagemap (chap, alias, ctx, line, path)
VALUES ($1, $2, $3::int, $4::int, $5::text::link[])
`

type InsertPageMapParams struct {
	Chap    *string `json:"chap"`
	Alias   *string `json:"alias"`
	Column3 int32   `json:"column_3"`
	Column4 int32   `json:"column_4"`
	Column5 string  `json:"column_5"`
}

func (q *Queries) InsertPageMap(ctx context.Context, arg InsertPageMapParams) error {
	_, err := q.db.Exec(ctx, insertPageMap,
		arg.Chap,
		arg.Alias,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	return err
}

const listPageMap = `-- name: ListPageMap :many
SELECT chap,
       ctx,
       line,
       path::text AS path
FROM pagemap
WHERE match_context(ctx, COALESCE($1::text[], ARRAY[]::text[])) = true
  AND lower(chap) LIKE lower($2)
ORDER BY chap, line
OFFSET $3
LIMIT $4
`

type ListPageMapParams struct {
	Column1 []string `json:"column_1"`
	Lower   string   `json:"lower"`
	Offset  int32    `json:"offset"`
	Limit   int32    `json:"limit"`
}

type ListPageMapRow struct {
	Chap *string `json:"chap"`
	Ctx  *int32  `json:"ctx"`
	Line *int32  `json:"line"`
	Path string  `json:"path"`
}

func (q *Queries) ListPageMap(ctx context.Context, arg ListPageMapParams) ([]ListPageMapRow, error) {
	rows, err := q.db.Query(ctx, listPageMap,
		arg.Column1,
		arg.Lower,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPageMapRow{}
	for rows.Next() {
		var i ListPageMapRow
		if err := rows.Scan(
			&i.Chap,
			&i.Ctx,
			&i.Line,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPageMapChapters = `-- name: ListPageMapChapters :many
SELECT DISTINCT chap, ctx
FROM pagemap
WHERE match_context(ctx, COALESCE($1::text[], ARRAY[]::text[]))
  AND (
    $2::boolean
    OR (
      CASE
        WHEN $3::boolean THEN lower(unaccent(chap)) LIKE lower($4)
        ELSE lower(chap) LIKE lower($4)
      END
    )
  )
ORDER BY chap
`

type ListPageMapChaptersParams struct {
	Column1 []string `json:"column_1"`
	Column2 bool     `json:"column_2"`
	Column3 bool     `json:"column_3"`
	Lower   string   `json:"lower"`
}

type ListPageMapChaptersRow struct {
	Chap *string `json:"chap"`
	Ctx  *int32  `json:"ctx"`
}

func (q *Queries) ListPageMapChapters(ctx context.Context, arg ListPageMapChaptersParams) ([]ListPageMapChaptersRow, error) {
	rows, err := q.db.Query(ctx, listPageMapChapters,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Lower,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPageMapChaptersRow{}
	for rows.Next() {
		var i ListPageMapChaptersRow
		if err := rows.Scan(&i.Chap, &i.Ctx); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
