// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	DeleteEdgesForNode(ctx context.Context, arg DeleteEdgesForNodeParams) error
	DeleteNodesByChapter(ctx context.Context, chap string) error
	GetContextByPtr(ctx context.Context, ctxPtr int32) (ContextDirectory, error)
	GetContextByText(ctx context.Context, argContext string) (ContextDirectory, error)
	GetLastSeenByNPtr(ctx context.Context, arg GetLastSeenByNPtrParams) (GetLastSeenByNPtrRow, error)
	GetNeighboursByType(ctx context.Context, arg GetNeighboursByTypeParams) ([]GetNeighboursByTypeRow, error)
	GetNodeByPtr(ctx context.Context, arg GetNodeByPtrParams) (GetNodeByPtrRow, error)
	GetNodeByText(ctx context.Context, lower string) (GetNodeByTextRow, error)
	InsertArrow(ctx context.Context, arg InsertArrowParams) error
	InsertArrowInverse(ctx context.Context, arg InsertArrowInverseParams) error
	InsertBookmark(ctx context.Context, arg InsertBookmarkParams) error
	InsertContext(ctx context.Context, arg InsertContextParams) error
	InsertEdge(ctx context.Context, arg InsertEdgeParams) error
	InsertLastSeenSection(ctx context.Context, section *string) error
	InsertNode(ctx context.Context, arg InsertNodeParams) error
	InsertPageMap(ctx context.Context, arg InsertPageMapParams) error
	ListArrowInverses(ctx context.Context) ([]ArrowInverse, error)
	ListArrows(ctx context.Context) ([]ArrowDirectory, error)
	ListBookmarks(ctx context.Context) ([]Bookmark, error)
	ListChaptersLike(ctx context.Context, lower string) ([]string, error)
	ListChaptersLikeUnaccent(ctx context.Context, lower string) ([]string, error)
	ListContexts(ctx context.Context) ([]ContextDirectory, error)
	ListEdgesFrom(ctx context.Context, arg ListEdgesFromParams) ([]Edge, error)
	ListEdgesFromByST(ctx context.Context, arg ListEdgesFromBySTParams) ([]Edge, error)
	ListEdgesTo(ctx context.Context, arg ListEdgesToParams) ([]Edge, error)
	ListLastSeen(ctx context.Context) ([]ListLastSeenRow, error)
	ListPageMapByContext(ctx context.Context, dollar_1 []string) ([]PageMap, error)
	ListPageMapDistinctChapCtx(ctx context.Context, dollar_1 []string) ([]ListPageMapDistinctChapCtxRow, error)
	ListRecentNPtrs(ctx context.Context, hours int32) ([]ListRecentNPtrsRow, error)
	MaxCPtrForClass(ctx context.Context, class int32) (int32, error)
	MaxCtxPtr(ctx context.Context) (int32, error)
	SearchNodesExact(ctx context.Context, arg SearchNodesExactParams) ([]SearchNodesExactRow, error)
	SearchNodesLike(ctx context.Context, arg SearchNodesLikeParams) ([]SearchNodesLikeRow, error)
	SearchNodesTsquery(ctx context.Context, arg SearchNodesTsqueryParams) ([]SearchNodesTsqueryRow, error)
	SearchNodesTsqueryUnaccent(ctx context.Context, arg SearchNodesTsqueryUnaccentParams) ([]SearchNodesTsqueryUnaccentRow, error)
	UpdateNodeChapter(ctx context.Context, arg UpdateNodeChapterParams) error
	UpdateNodeSeq(ctx context.Context, arg UpdateNodeSeqParams) error
}

var _ Querier = (*Queries)(nil)
