// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	ListBookmarks(ctx context.Context) ([]ListBookmarksRow, error)
	ListChaptersLike(ctx context.Context, lower string) ([]*string, error)
}

var _ Querier = (*Queries)(nil)
