// Command cssgen expands internal/css/style.css.in into theme CSS files
// under internal/server/public/. Invoked via go:generate.
package main

import (
	"bufio"
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/markburgess/SSTorytime/internal/css"
)

var (
	ErrNoThemeVars = errors.New("no theme vars")
	ErrNoGoMod     = errors.New("go.mod not found")
)

func main() {
	root, err := moduleRoot()
	if err != nil {
		fail(err)
	}
	inPath := filepath.Join(root, "internal", "css", "style.css.in")
	outDir := filepath.Join(root, "internal", "server", "public")

	raw, err := os.ReadFile(inPath)
	if err != nil {
		fail(err)
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		fail(err)
	}

	vars := css.ThemeVars()
	for _, name := range css.ThemeNames {
		v, ok := vars[name]
		if !ok {
			fail(fmt.Errorf("%w: %q", ErrNoThemeVars, name))
		}
		out := expand(raw, v)
		outPath := filepath.Join(outDir, name+".css")
		header := fmt.Sprintf("/* generated by go run ./internal/libexec/cssgen — do not edit; source internal/css/style.css.in */\n")
		if err := os.WriteFile(outPath, append([]byte(header), out...), 0o644); err != nil {
			fail(err)
		}
		fmt.Println("wrote", outPath)
	}
}

func expand(raw []byte, vars map[string]string) []byte {
	var buf bytes.Buffer
	sc := bufio.NewScanner(bytes.NewReader(raw))
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := sc.Text()
		for token, val := range vars {
			if strings.Contains(line, token) {
				line = strings.Replace(line, token, val, 1)
			}
		}
		buf.WriteString(line)
		buf.WriteByte('\n')
	}
	if err := sc.Err(); err != nil {
		fail(err)
	}
	return buf.Bytes()
}

func moduleRoot() (string, error) {
	// Prefer cwd when run as `go run ./internal/libexec/cssgen` from module root.
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	dir := wd
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("%w: from %s", ErrNoGoMod, wd)
		}
		dir = parent
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "cssgen:", err)
	os.Exit(1)
}
